# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "xhci_pci" "usb_storage" "sd_mod" "sr_mod" "sdhci_pci" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/1b3ce7ef-ee87-48b8-8bb0-0f8ec3825c35";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/b6bc02f7-c395-4825-afe3-390b87b47e7d";
      fsType = "ext3";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/3c4d3a44-29d0-4e8f-9dad-7d6a3c594497"; }
    ];

  nix.maxJobs = lib.mkDefault 4;
}
